### ISSUE TITLE
N'est plus à jour

### ISSUE THREAD

**Issue by CobKurtain** [Airmime/chrome-app-twitch-alert#1]
Salut Rémi,
Est-il possible pour toi de mettre à jour cette app ?

**Comment by Airmime** [comment]
Salut,

Effectivement, l'API Twitch a pas mal évoluée.
Néanmoins, je ne compte pas mettre à jour cette extension.

Si besoin tu peux forker le dépôt, et faire les modifications nécessaires.

Rémi
